version: '3'
services:
  mongo:
    image: mongo
    volumes:
    - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  redis:
    image: redis
    volumes:
    - ./data/redis:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=secret

  website:
    build: .
    ports:
      - "8000:8080"
    env_file:
      - conf/.env
    depends_on:
      - mongo
      - redis
      - elasticsearch